networks:
  postgres_network:
services:
  postgres:
   container_name: postgres_cnt2
   image: postgres:17
   restart: always
   environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
   ports:
    - "5433:5433"
   networks:
    - postgres_network
   volumes:
    - ./postgres_data:/var/lib/postgresql/data
   healthcheck:
    test: ["CMD-SHELL", "pg_isready -d dw -U dw_dev"]
    interval: 1s
    timeout: 5s
    retries: 10
  pgadmin4:
   container_name: pgadmin4_cnt2
   image: dpage/pgadmin4
   environment:
    PGADMIN_DEFAULT_EMAIL: brunoaraujo@fiepb.org.br
    PGADMIN_DEFAULT_PASSWORD: password
   ports:
    - "8000:80"
   depends_on:
    - postgres
   restart: always
   networks:
    - postgres_network
   volumes:
   - ./pgadmin_data:/var/lib/pgadmin
